<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x86</PlatformTarget>
	<RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
<ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
</ItemGroup>
<ItemGroup>
  <Reference Include="AOItemQueryService">
    <HintPath>..\AOItemQueryService\bin\Debug\net10.0-windows\win-x86\AOItemQueryService.dll</HintPath>
  </Reference>
  <Reference Include="AOSharp.Common">
    <HintPath>..\AOSharp.Net\bin\Release\net10.0-windows\Plugins\AOSharp.Common\AOSharp.Common.dll</HintPath>
  </Reference>
  <Reference Include="AOSharp.Core">
    <HintPath>..\AOSharp.Net\bin\Release\net10.0-windows\Plugins\AOSharp.Core\AOSharp.Core.dll</HintPath>
  </Reference>
</ItemGroup>
  <ItemGroup>
    <None Update="manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="MissionLevels.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ProjectExtensions><VisualStudio><UserProperties manifest_1json__JsonSchema="https://www.schemastore.org/function.json" /></VisualStudio></ProjectExtensions>
</Project>